CHANGELOG.md
lib/openhab/core/items/item.rb
lib/openhab/core/items/semantics/enumerable.rb
lib/openhab/core_ext/ruby/module.rb
spec/openhab/core/items/item_spec.rb

add predicates for easily checking item membership

---

docs/examples.md

to delete gem directories from other jruby versions when using a unique gem_home for each version.

Update gem cleanup example

---

.github/workflows/ci.yml
.markdownlint.yaml
.pre-commit-config.yaml
CHANGELOG.md
CONTRIBUTING.md
README.md
USAGE.md
docs/examples.md
docs/ruby-basics.md
docs/testing.md

with rules based on openhab-docs

enable markdown linting

---

.github/workflows/ci.yml

it's what's actually in openhab 3.4.2

ci: update to jruby 9.3.10.0

---

lib/openhab/dsl/rules/automation_rule.rb

This part gets called for every event

combine two logger calls

---

lib/openhab/core/rules/rule.rb

handle Rules.manager being nil

---

.github/workflows/yardoc.yml

allow manually calling yardoc workflow

---

USAGE.md

It's currently quite obscure, you'd have to know it's there.

add information about Profiles in USAGE.md

---

lib/openhab/core/items/semantics.rb
spec/openhab/core/items/semantics_spec.rb

The main feature has been merged into core https://github.com/openhab/openhab-core/pull/3519
It may not make it into snapshot until later today.

Semantic Tag improvements: support tag attributes, tag lookup, and adding tags

---

.github/workflows/ci.yml

update to 3.4.3, add 4.0.0.M2 in addition to snapshot, and simplify the java 11/17 logic (always use 11 for 3.4.x, 17 for 4.x)

update CI matrix

---

lib/openhab/dsl/rules/triggers/conditions/duration.rb
spec/openhab/dsl/rules/builder_spec.rb

They now act the same as if you had passed an array of items the trigger - namely that each item gets its own timer, and one item in the group changing does not cancel the timer for  all other items in the group (or worse, losing events because one item is in the proper state, but another changed without matching the from/to conditions).

Fix duration trigger conditions for group member triggers

---

lib/openhab/core/rules/registry.rb
lib/openhab/core/rules/tagged_array.rb
lib/openhab/dsl.rb
lib/openhab/dsl/rules/automation_rule.rb
lib/openhab/dsl/rules/builder.rb
spec/openhab/dsl/rules/builder_spec.rb
spec/openhab/dsl_spec.rb

Add `scene` helper method to easily create rules tagged as Scene

---

.rubocop.yml

exclude more stuff from rubocop

---

lib/openhab/dsl/rules/builder.rb
lib/openhab/dsl/rules/triggers/cron/cron_handler.rb
spec/openhab/dsl/rules/builder_spec.rb

So they show up on the calendar in MainUI

Tag `cron`, `every`, and `at` triggers with "Schedule"

---

lib/openhab/core/items/generic_item.rb
lib/openhab/rspec/karaf.rb
spec/openhab/core/items/item_spec.rb

instead of rolling our own duplicated code
fixes #81

Fix unit conversions in Item#formatted_state

---

USAGE.md

update USAGE.md to reflect looser default version requirements

---

.github/workflows/ci.yml
rakelib/openhab.rake

Setting the system property `jdk.util.zip.disableZip64ExtraFieldValidation=true` didn't seem to fix the issue.

Use java version before the changes in zip policy

---

lib/openhab/log.rb

backtrace_locations can return nil

---

lib/openhab/core/items/persistence.rb
spec/openhab/core/items/persistence_spec.rb

https://github.com/openhab/openhab-core/pull/3466

Support all_states_since and all_states_between persistence methods

---

templates/default/layout/markdown/setup.rb

See https://github.com/openhab/openhab-addons/pull/15435

Change addon's readme images to `doc/`

---

lib/openhab/dsl/timer_manager.rb

Make the references clickable in YARD

Fix doc references to Core::Timer

---

lib/openhab/dsl/rules/builder.rb
spec/openhab/dsl/rules/builder_spec.rb

Don't tag `cron`, `every`, and `at` triggers with "Schedule"

---

lib/openhab/dsl/rules/triggers/cron/cron.rb
lib/openhab/dsl/rules/triggers/cron/cron_handler.rb

See https://github.com/openhab/openhab-core/pull/2965

Use the default cron handler in openHAB 4

---

docs/examples.md

There's a lot of confusion over openhab's executeCommandLine

Add examples for executing external commands

---

lib/openhab/core/items/group_function.rb
lib/openhab/core/items/group_item.rb
spec/openhab/core/items/group_item_spec.rb

Note this needs #126 in order to pass the spec.

Add group function #to_s and #inspect

---

lib/openhab/core/events/abstract_event.rb
lib/openhab/core/events/timer_event.rb
spec/openhab/core/events/timer_event_spec.rb

This may be useful especially for UI rules

Add event attributes for TimerEvent

---

lib/openhab/core/items/group_item.rb
lib/openhab/core/items/item.rb
spec/openhab/core/items/color_item_spec.rb
spec/openhab/core/items/contact_item_spec.rb
spec/openhab/core/items/date_time_item_spec.rb
spec/openhab/core/items/dimmer_item_spec.rb
spec/openhab/core/items/group_item_spec.rb
spec/openhab/core/items/image_item_spec.rb
spec/openhab/core/items/location_item_spec.rb
spec/openhab/core/items/number_item_spec.rb
spec/openhab/core/items/player_item_spec.rb
spec/openhab/core/items/rollershutter_item_spec.rb
spec/openhab/core/items/string_item_spec.rb
spec/openhab/core/items/switch_item_spec.rb

closes #119
in particular, group item will also check its base_item

add item type predicates

---

lib/openhab/log.rb

See https://github.com/openhab/openhab-jruby/pull/152

Initialize `$ctx` to suppress warnings

---

lib/openhab/dsl/items/builder.rb
spec/openhab/dsl/items/builder_spec.rb

Fix entity lookup inside item builder's item block

---

USAGE.md

In response to https://github.com/openhab/openhab-addons/pull/15624#discussion_r1337603927

Avoid having lines with multiple split sentences

---

lib/openhab/rspec/helpers.rb
lib/openhab/rspec/karaf.rb

Fix rspec errors in oh41-snapshot

OH41-snapshot loads jetty.http2.hpack and needs dsl:rules readymarker

---

spec/openhab/core/types/point_type_spec.rb

add specs for PointType accessors

---

lib/openhab/core/things/proxy.rb
lib/openhab/core/things/thing.rb
spec/openhab/core/things/thing_spec.rb

I'm not really sure this is necessary, so feel free to close it.

Refactor ChannelsArray lookup by channel id and uid

---

lib/openhab/dsl/things/builder.rb
spec/openhab/dsl/things/builder_spec.rb

Fix Bridge Builder and allow nested Thing

---

USAGE.md
lib/openhab/dsl.rb
lib/openhab/dsl/rules/builder.rb
spec/openhab/dsl/rules/builder_spec.rb

Add tags and description to #script and #scene

---

lib/openhab/dsl/sitemaps/builder.rb
spec/openhab/dsl/sitemaps/builder_spec.rb

Support staticIcon and dynamic icon in sitemap

---

lib/openhab/dsl/sitemaps/builder.rb
spec/openhab/dsl/sitemaps/builder_spec.rb

Support Buttongrid in Sitemap Builder

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/yardoc.yml

update rubygems in CI

---

lib/openhab/core/sitemaps/provider.rb
lib/openhab/dsl/sitemaps/builder.rb
spec/openhab/dsl/sitemaps/builder_spec.rb

by accepting a block argument
this allows direct access to the calling context to call methods on

allow _not_ using instance_exec with sitemap builder

---

CHANGELOG.md

I've also updated GH release https://github.com/openhab/openhab-jruby/releases/tag/v5.15.0

manually add #227 to v5.15.0 changelog

---

docs/conversions.md

@giskard from the forums [pointed out](https://community.openhab.org/t/error-with-openhab-py-script-100-directorytrigger-py-after-update-to-4-0-1/148199/72) that Python doesn't have a `&&` operator.

fix python example

---

lib/openhab/core/sitemaps/provider.rb
lib/openhab/dsl/sitemaps/builder.rb
spec/openhab/dsl/sitemaps/builder_spec.rb

Fix dummy items when using sitemap proxy builder

---

docs/testing.md

"Cans" might be a regional name for this type of light, that others may not understand

change example to more easily understood "Downlights"

---

lib/openhab/core/dto/item_channel_link.rb
lib/openhab/dsl/rules/builder.rb
spec/openhab/dsl/rules/builder_spec.rb

Support filtered item|thing_added|removed and channel_linked|unlinked triggers

---

.github/workflows/ci.yml

There are some updates/fixes in #244 that need to be merged for the tests to pass

Update CI to jruby 9.4.7.0

---

lib/openhab/dsl/sitemaps/builder.rb

https://github.com/openhab/openhab-core/pull/4084

Sitemaps: add `release_only` option for `slider`

---

lib/openhab/core/items/persistence.rb
spec/openhab/core/items/persistence_spec.rb

Depends on: https://github.com/openhab/openhab-core/pull/4259

Persistence: add `last_change` and `next_change`

---

lib/openhab/core/items/call_item.rb
lib/openhab/core/items/item.rb
lib/openhab/core/types/string_list_type.rb
lib/openhab/dsl/items/builder.rb
spec/openhab/core/items/call_item_spec.rb
spec/openhab/core/types/string_list_type_spec.rb
spec/openhab/dsl/items/builder_spec.rb

Add `CallItem` and `StringListType` support

---

USAGE.md
lib/openhab/dsl/rules/builder.rb

Improve docs for DateTimeTrigger

---

lib/openhab/core/items/persistence.rb
lib/openhab/core/types/quantity_type.rb
spec/openhab/core/items/persistence_spec.rb

I forgot multiplications in the previous PR

Persistence: support multiplication with PersistedState

---

lib/openhab/dsl/rules/builder.rb
lib/openhab/dsl/rules/triggers/changed.rb
spec/openhab/dsl/rules/builder_spec.rb

Note, triggers on item "*" isn't currently supported in core, so it's not added here.

Allow changed trigger on any Thing

---

lib/openhab/dsl/items/timed_command.rb
spec/openhab/dsl/items/timed_command_spec.rb

It's useful to know whether a timed command is currently active.
Example:
```ruby
rule "Motion Detected" do
received_command Motion_Sensor, command: ON
run do
next if FrontPorchLight.on? && !FrontPorchLight.timed_command?
FrontPorchLight.ensure.on for: 30.minutes
end
end
```
Caveat: only works in the same file, but the whole timed command map lives in the file scope anyway.

Add TimedCommand parameter `only_when_ensured`

---

.github/workflows/ci.yml
lib/openhab/core.rb

Support Milestones and RC versions

---

lib/openhab/dsl/rules/triggers/cron/cron.rb
spec/openhab/dsl/rules/builder_spec.rb

`every :monday` should mean once on the day, at midnight, not every second

Fix `every` day-of-week trigger

---

lib/openhab/core/types/time_series.rb
spec/openhab/core/types/time_series_spec.rb

TimeSeries: add `#<<` convenience method and refactor with LazyArray

---

lib/openhab/dsl/rules/builder.rb
lib/openhab/dsl/rules/triggers/cron/cron.rb
spec/openhab/dsl/rules/builder_spec.rb

Support `every(:monday, :wednesday, :friday)`

Support `every` trigger with multiple days of week.

---

lib/openhab/core/profile_factory.rb
lib/openhab/dsl.rb
spec/openhab/dsl_spec.rb

Example usage https://community.openhab.org/t/profile-to-cycle-through-a-list-of-values-upon-event-trigger/157359/5?u=jimt

Support creating a trigger `profile`

---

lib/openhab/core/things/thing.rb
spec/openhab/core/things/thing_spec.rb

Add `Thing#bridge?`

---

lib/openhab/core.rb
lib/openhab/core/items/persistence.rb
spec/openhab/core/items/persistence_spec.rb

See https://github.com/openhab/openhab-core/pull/4345

Add median persistence methods

---

lib/openhab/core/events.rb
lib/openhab/core/events/abstract_event.rb
lib/openhab/core/events/channel_triggered_event.rb
lib/openhab/core/events/item_command_event.rb
lib/openhab/core/events/item_state_changed_event.rb
lib/openhab/core/events/item_state_event.rb
lib/openhab/core/events/thing_status_info_event.rb
lib/openhab/core/items/generic_item.rb
lib/openhab/core/items/group_item.rb
lib/openhab/dsl/items/ensure.rb
lib/openhab/dsl/items/timed_command.rb
spec/openhab/core/events/item_command_event_spec.rb
spec/openhab/core/events/item_state_changed_event_spec.rb
spec/openhab/core/events/item_state_event_spec.rb
spec/openhab/core/events/item_state_updated_event_spec.rb
spec/openhab/core/items/item_spec.rb

And document the source field on events, and add several inspect methods to more easily debug events with sources.

Allow sending source with commands

---

lib/openhab/core/items/generic_item.rb

that's what it's called in the sitemap builder, and what it's effectively for now

alias GenericItem#category to GenericItem#icon

---

lib/openhab/core/items/persistence.rb
lib/openhab/rspec/mocks/persistence_service.rb
spec/openhab/core/items/persistence_spec.rb

See https://github.com/openhab/openhab-core/pull/4384

Add PersistedState#instant

---

lib/openhab/core/types/date_time_type.rb
spec/openhab/core/types/date_time_type_spec.rb
spec/openhab/core_ext/ephemeris_spec.rb

Due to https://github.com/openhab/openhab-core/pull/3583

Fix specs broken in 4.3

---

.github/workflows/ci.yml
lib/openhab/core/items/semantics.rb

See also https://github.com/jruby/jruby/issues/8526

Fix semantic tag lookup on Java 21

---

lib/openhab/dsl/rules/builder.rb

See https://github.com/openhab/openhab-core/issues/4590

Fix disabled rule remains disabled

---

lib/openhab/core/items/registry.rb
lib/openhab/dsl/items/builder.rb

See https://community.openhab.org/t/jruby-items-builder-persistance/162401/16

Add an example for `items.build(:persistent)`

---

USAGE.md

It seems that unless we mention it in the main usage doc, people might not realise that these features existed unless they dig (much) deeper, and being unfamiliar with the docs puts them at a disadvantage.

Add watch trigger and thing builder to usage doc

---

.github/workflows/ci.yml

There's a fix for persistence spec in #402

Update CI to openHAB 4.3.3 and add 5.0.0.M1

---

lib/openhab/core/items/generic_item.rb
spec/openhab/core/items/item_spec.rb

```ruby
Super_Long_Item_Name_Because_Thats_How_I_Roll.modify do |item|
item.label = "I'm super long"
item.icon = :switch
item.tags = Semantics::Switch
end
```

Pass self to Item#modify block

---

rakelib/openhab.rake

This is so running irb console inside the jrubyscripting console (karaf command) would work on the test build.

Add HOME and PATH to openhab_env for the test build

---

.rubocop.yml
.yardopts
lib/openhab/console.rb
lib/openhab/console/irb.rb
lib/openhab/console/jline.rb
lib/openhab/console/registry.rb
lib/openhab/console/stdio.rb

Add console script to be used by the add-on Karaf console command

 Add console scripts for Karaf console

---

Gemfile
Gemfile.lock
lib/openhab/console/irb.rb
lib/openhab/console/stdio.rb
openhab-scripting.gemspec
spec/openhab/console/irb_spec.rb
spec/openhab/console/stdin_spec.rb
spec/spec_helper.rb

so that we know we have a useful version

add irb as an explicit dependency, and basic console specs

---

.yard/config
lib/openhab/dsl/rules/builder.rb
lib/openhab/dsl/sitemaps/builder.rb

Wait until OH 5.0 is released before switching?

Update javadocs links to Java 21

---

Gemfile
Gemfile.lock
openhab-scripting.gemspec

jar-dependencies/psych are giving us heartburn

remove direct irb dependency

---

USAGE.md

https://github.com/openhab/openhab-addons/pull/18030#discussion_r1903109584

RulesDSL -> Rules DSL

---

lib/openhab/scripting.rb

This is to support the Gemfile feature in https://github.com/openhab/openhab-addons/pull/18404

Add a default file so Gemfile doesn't need a custom require

---

lib/openhab/core.rb
lib/openhab/dsl/rules/builder.rb
lib/openhab/dsl/rules/triggers/changed.rb
lib/openhab/dsl/rules/triggers/command.rb
lib/openhab/dsl/rules/triggers/updated.rb
spec/openhab/dsl/rules/builder_spec.rb

Support https://github.com/openhab/openhab-core/pull/4646

Support wildcard item and improve wildcard thing triggers

---

.rubocop.yml
lib/openhab/console.rb
spec/spec_helper.rb

See https://github.com/openhab/openhab-addons/pull/18529

Resolve $terminal from $console

---

USAGE.md

Docs for https://github.com/openhab/openhab-addons/pull/18404 and https://github.com/openhab/openhab-addons/pull/18374

Document console commands and bundle_gemfile setting

---

lib/openhab/core/items/image_item.rb

Don't require base64

---

lib/openhab/core_ext/java/list.rb

avoids https://github.com/jruby/jruby/issues/8767

use `itr` instead of `it` for iterator

---

lib/openhab/core/items/item.rb

It might not work anyway, given this is a Java object

Don't memoize Item#metadata

---

lib/openhab/core/items/semantics.rb
spec/openhab/core/items/semantics_spec.rb

Allow searching for multiple points or properties, or specific combinations thereof.

Enhance flexibility of #points

---

lib/openhab/core/value_cache.rb

Ref: https://github.com/openhab/openhab-core/pull/4704

Document OH5's ValueCache#compute

---

lib/openhab/core_ext/ruby/object.rb
lib/openhab/dsl.rb

Instead of a custom instance variable on Object's class.

Use TOPLEVEL_BINDING.receiver to get at `main`

---

.github/workflows/ci.yml

Also update to the latest OH 4.3.6

Update CI against openhab 5.1 snapshot
