openhab/openhab-jruby

- .github/workflows/release.yml
- Gemfile.lock
- lib/openhab/dsl/version.rb
- openhab-jrubyscripting.gemspec
this has been tested in my own repo at https://github.com/ccutrer/openhab-jruby/actions/runs/4226468917/jobs/7339936590, resulting in commit https://github.com/ccutrer/openhab-jruby/commit/f13bbe7b60c211b85b49c52b6731815321ddc522 and gem https://rubygems.org/gems/openhab-jrubyscripting/versions/5.0.0.rc.13
it's manually triggered for now, you just get to specify how much to bump the gem version
> add gem release action

- .github/workflows/release.yml
since when you're on say 5.0.0.rc.12, doing a "major" release puts you on 6.0.0!
> adjust options for next release version

- USAGE.md
Because the addon will [install the gem by default](https://github.com/openhab/openhab-addons/pull/14489), remove the instructions to configure it from the installation instructions.
> Simplify installation instructions

- lib/openhab/dsl/timer_manager.rb
- spec/openhab/core/timer_spec.rb
Fix a bug where a nested reentrant timer would continue to execute even after the timer has been cancelled by its id.
> fix nested reentrant timer

- lib/openhab/core/timer.rb
- lib/openhab/dsl/timer_manager.rb
- lib/openhab/rspec/mocks/timer.rb
- spec/openhab/core/timer_spec.rb
Timers#reschedule worked on timers without id, the same way openHAB's timers do, but it didn't work when the timer had an id. This PR fixed this problem.
> fix #reschedule on timers with id after it has terminated

- lib/openhab/dsl/rules/name_inference.rb
- spec/openhab/dsl/rules/name_inference_spec.rb
apparently at some point the sentence structure changed
spec added so it won't regress again
> fix name inference for multiple items

- CHANGELOG.md
- lib/openhab/core/actions/audio.rb
I'm not sure where this issue lies. 
I'm not sure if this is a bug in 9.4.2.0 that surfaced because Audio.playSound recently got a new overloaded method?
So two overloaded java methods with the same number of parameters, but different signatures.
I am calling the java method with `Audio.playSound(nil, "soundfile", PercentType.new(100))`
It is supposed to call this: https://www.openhab.org/javadoc/latest/org/openhab/core/model/script/actions/audio#playSound(java.lang.String,java.lang.String,org.openhab.core.library.types.PercentType)
but instead I got an error indicating that it's trying to call this
https://www.openhab.org/javadoc/latest/org/openhab/core/model/script/actions/audio#playSound(java.lang.String,java.lang.String,float)
This is the error/exception from my log:
`for method …
> fix Audio.play_sound with volume

- .github/workflows/ci.yml
The addon is set to 9.4 https://github.com/openhab/openhab-addons/pull/14556
> remove jruby9.3 from oh4 ci

- CHANGELOG.md
- lib/openhab/core/events/item_state_updated_event.rb
- spec/openhab/core/events/item_state_updated_event_spec.rb
- spec/openhab/dsl/rules/builder_spec.rb
ItemStateUpdatedEvent was added here: https://github.com/openhab/openhab-core/pull/3141
`updated` rules couldn't get `event.state` because of it.
> support ItemStateUpdatedEvent

- lib/openhab/dsl.rb
I'm not sure what to do regarding the [@overload](https://github.com/openhab/openhab-jruby/compare/main...jimtng:provider-docs?expand=1#diff-f28698d5180c99b407383b3925e5d0d166fed423d20216aa0a0c7d5d41ef34b5R818). It appears that it was planned to have two versions of the method signature but forgot to complete it.
> Fix DSL.provider doc

- .github/workflows/release.yml
- Gemfile.lock
- openhab-scripting.gemspec
I'm not really sure what the problem is with the generator. It appeared to be intermittent, and faraday-retry might help.
It seems that the `rake changelog` caused some changes in Gemfile.lock, so it needed to be staged and committed before running rake release.
> Fix release workflow

- .known_good_references
- lib/openhab/core/items/semantics.rb
- spec/openhab/core/items/semantics_spec.rb
- spec/openhab/core/types/hsb_type_spec.rb
- spec/openhab/dsl/rules/builder_spec.rb
This fixes errors such as
```
org.jruby.exceptions.TypeError: (TypeError) compared with non class/module
at org.jruby.RubyModule.<=(org/jruby/RubyModule.java:2845) ~[?:?]
at org.jruby.RubyModule.<(org/jruby/RubyModule.java:2879) ~[?:?]
at RUBY.points(/etc/openhab/automation/ruby/.gem/9.4.2.0/gems/openhab-scripting-5.1.0/lib/openhab/core/items/semantics.rb:625) ~[?:?]```
> fix version detection against 4.0.0.M*

- lib/openhab/core/actions/audio.rb
The previous fix in #43 didn't work.
> Audio.play_sound called the wrong Java method

- .github/workflows/ci.yml
- USAGE.md
- lib/openhab/dsl/items/builder.rb
- spec/openhab/core/items/number_item_spec.rb
- spec/openhab/core/items/persistence_spec.rb
- spec/openhab/core/types/quantity_type_spec.rb
- spec/openhab/dsl/items/builder_spec.rb
- spec/openhab/dsl/items/ensure_spec.rb
sets the metadata, since this is now a very important metadata
in openHAB 4.0
also use it to introduce automatic inference of dimension and format,
making it cross-compatible between OH 3.4 and OH 4.0 (as long as
you're not using a custom format that makes OH 3.4 unable to detect
the unit).
updates CI to OH 4.0.0.M3, and OH 4.0 builds should now be passing
> Add unit argument to items builder

- lib/openhab/core_ext/ruby/object.rb
- lib/openhab/dsl.rb
so that DSL methods don't hide user methods
fixes #4
> Workaround unusual inheritance chain of `main`

- .github/workflows/ci.yml
- lib/openhab/core/items/item.rb
- lib/openhab/core/items/semantics.rb
- lib/openhab/core/items/semantics/provider.rb
- lib/openhab/core/items/semantics/semantic_tag.rb
- lib/openhab/core/items/semantics/tag_class_methods.rb
- lib/openhab/core/provider.rb
- lib/openhab/dsl/items/builder.rb
- lib/openhab/rspec/hooks.rb
- spec/openhab/core/items/semantics_spec.rb
They're now a registry and provider infrastructure, like all the other objects. Also, tags are instances of SemanticTag now, instead of simply interfaces that implement Tag.
> Rework semantics for openHAB 4.0.0.M5

- lib/openhab/rspec/helpers.rb
On OH4, Start Level 30 requires the readymarker from ScriptEngineFactoryBundleTracker to be set, but it isn't consistently set when karaf is started by rspec for some reason.
It appears that the bundle `org.openhab.automation.jrubyscripting` never entered the `ACTIVE` state.
So we set a dummy ready marker for it in order to satisfy the start level requirement.
> Fix intermittent rspec execution on OH4

- docs/testing.md
- lib/openhab/rspec.rb
Also update the docs to recommend a console script, rather than .irbrc
> Fix loading a console session of your own openHAB instance

- lib/openhab/dsl/rules/automation_rule.rb
this can happen during watch specs, with have a background thread, and thus trigger the event after the spec has completed
fixes #122
> handle RSpec.current_example being nil

- USAGE.md
When viewing the addon readme, especially from within the MainUI -> Addons page, the very bottom of the page is the link to "Calling Java from JRuby" like this, which might be a bit misleading to new users.
So this PR changed the way the link is presented.
> Link to the github pages at the bottom of USAGE.md

- lib/openhab/dsl/items/builder.rb
- spec/openhab/dsl/items/builder_spec.rb
In an .items file, the syntax is 
```
Group:Number:COUNT("regex") Groupname
```
Like in an .items file, the pattern inside the parentheses can optionally be enclosed with quotes, e.g. when it contains a comma, to ensure that it stays as a single argument to the function.
```ruby
items.build do
group_item GroupName, type: :number, function: 'COUNT("pattern,with,commas")'
group_item GroupName, type: :number, function: 'COUNT(simple pattern)'
end
```
> Fix item builder's group COUNT function

- USAGE.md
- lib/openhab/core/configuration.rb
- lib/openhab/core/emulate_hash.rb
- lib/openhab/core/items/metadata/hash.rb
- lib/openhab/core/items/metadata/namespace_hash.rb
- lib/openhab/core/things/links/provider.rb
- lib/openhab/core/things/thing.rb
- lib/openhab/dsl/rules/rule_triggers.rb
- lib/openhab/dsl/things/builder.rb
- spec/openhab/core/configuration_spec.rb
Also document additional Thing attributes.
Classes `Core::Items::Metadata::NamespaceHash` and `Core::Items::Metadata::Hash` were refactored and the common code moved into `EmulateHash`.
> Make Configuration objects more Ruby-like

- lib/openhab/core_ext/ruby/numeric.rb
- spec/openhab/core_ext/ruby/numeric_spec.rb
In case you're using it with StateDescription or any other Java object that returns Java's BigDecimal
> Add unit conversion operator (|) to java.math.BigDecimal

- lib/openhab/dsl/rules/builder.rb
- lib/openhab/dsl/rules/triggers/cron/cron.rb
- spec/openhab/dsl/rules/builder_spec.rb
These were broken because `dow` and `dom` look up into EXPRESSION_MAP failed.
```
cron dow: anything
cron dom: anything
```
> Fix defaults with cron fields `dow` and `dom`

- lib/openhab/core/types/quantity_type.rb
- spec/openhab/core/types/quantity_type_spec.rb
- spec/openhab/dsl_spec.rb
This PR addressed the following problems:
1. Operates under the rhs unit
```
a = QuantityType.new("20 °C")
b = QuantityType.new("9 °F")
logger.warn a + b # => 45 °F - this should be 25 °C 
logger.warn b + a # => 25 °C - this should be 45 °F
```
self gets converted to other's unit + other converted to self.unit then added to self. This gave the wrong result in the wrong unit.
The lhs just needs to be converted to the unit defined by the block, and rhs needs to be converted using `to_unit_relative` to the unit defined by the block.
2. Inside a unit block
```
a = QuantityType.new("20 °C")
b = QuantityType.new("9 °F")
unit("°C") do
logger.warn a + b # => 7.2222 °C => This should be 25 °C
logger.warn b + a # => 7.2222 °C => correct. 9 °F + 20 °C -> -12.78 °C + 20 °C
logger.warn 2 + b # -> - …
```
> Fix QuantityType arithmetic of mixed units

- lib/openhab/core/items/semantics.rb
SemanticTags.add was only in core for a short time, and not during any full release.
> Drop openHAB 4.0 snapshot compatibility

- lib/openhab/core/timer.rb
See https://github.com/openhab/openhab-core/pull/2911
just so the block location shows up in log. Instead of `<unknown>`
```
12:55:46.968 [WARN ] [core.internal.scheduler.SchedulerImpl] - Scheduled job '<unknown>' failed and stopped
org.jruby.exceptions.RuntimeError: (RuntimeError) 
at RUBY.<main>(/openhab/conf/automation/ruby/rules/test2.rb:1) ~[?:?]
```
It would log as:
```
13:06:14.784 [WARN ] [core.internal.scheduler.SchedulerImpl] - Scheduled job '/openhab/conf/automation/ruby/rules/test2.rb:1' failed and stopped
org.jruby.exceptions.RuntimeError: (RuntimeError) 
at RUBY.<main>(/openhab/conf/automation/ruby/rules/test2.rb:1) ~[?:?]
```
We could also allow for specifying a custom identifier but it doesn't have much use beyond the error message in the log.
> Use block's source location as timer's log identifier

- lib/openhab/dsl/items/builder.rb
- lib/openhab/dsl/things/builder.rb
- spec/openhab/dsl/items/builder_spec.rb
Since we allow symbolic channel name in channel builder, this also allows it in item builder.
```ruby
things.build do
thing "xxx" do
channel :channelname, "string"
end
end
items.build do
string_item MyItem, thing: "xxx" do
channel :channelname
end
end
```
> Allow symbolic channel name in ItemBuilder

- lib/openhab/core/items/metadata/hash.rb
- lib/openhab/dsl/items/builder.rb
- spec/openhab/dsl/items/builder_spec.rb
`expire` can accept `ignoreStateUpdates` and `ignoreCommands` options
```ruby
items.build do
switch_item Switch1, expire: [5.seconds, { ignore_state_updates: true }]
switch_item Switch2 do
expire 5.seconds, ignore_commands: true
end
config = { 
expire: [5.seconds, { ignore_commands: true }], 
}
switch_item Switch3, **config
end
```
> Support expire configuration options in Item Builder

- lib/openhab/dsl/items/builder.rb
- spec/openhab/dsl/items/builder_spec.rb
Since `groups` is advertised as a fluent alias for `group`, one should be able to pass a single group item (not an array of groups) to `groups` like this:
```ruby
items.build do
number_item Test1, groups: gMyGroup
end
```
This worked fine.
The bug is when it's done inside a group_item's block
```ruby
items.build do
group_item MyGroup do
number_item Test1, groups: SomeOtherGroup
end
end
```
Suddenly SomeOtherGroup will receive commands because inside GroupItemBuilder it does `groups << self` expecting that it's an array when it isn't. We need to wrap the variable `groups` in an array if it isn't one.
> Fix a non-array passed to item's `groups` argument inside group block

- .rubocop.yml
- lib/openhab/core/items/item.rb
- lib/openhab/core/items/metadata/hash.rb
- spec/openhab/core/items/metadata/hash_spec.rb
- spec/openhab/rspec/helpers_spec.rb
Fixes #161
So that the plain form acts like it does on other objects... simply returning the current provider (even if not managed), or nil if it doesn't actually exist yet.
> Split Metadata::Hash#provider to provider and provider!

- lib/openhab/core/types/point_type.rb
This was due to a Units vs SIUnits confusion that other parts of this file however handled correctly.
Fixes issue #173
Signed-off-by: Ulrich Spörlein <uspoerlein@gmail.com>
> Fix latitude/longitude/altitude getters on Location objects

- lib/openhab/core/emulate_hash.rb
- lib/openhab/core/items/group_item.rb
- lib/openhab/core/items/item.rb
- lib/openhab/core/items/number_item.rb
- lib/openhab/core/items/registry.rb
- lib/openhab/core/registry.rb
- lib/openhab/core/sitemaps/provider.rb
- lib/openhab/core/things/links/provider.rb
- lib/openhab/core/things/registry.rb
- lib/openhab/core/things/thing.rb
- lib/openhab/dsl/items/builder.rb
- lib/openhab/dsl/sitemaps/builder.rb
- lib/openhab/dsl/things/builder.rb
- spec/openhab/core/items/registry_spec.rb
- spec/openhab/dsl/items/builder_spec.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
- spec/openhab/dsl/things/builder_spec.rb
Also includes some minor bug fixes
- notify_listeners_about_updated_element(_old_element, element) needed two parameters
- do an identity lookup for elementToProvider. Note, I tried `.to_h.compare_by_identity`, but it didn't do as expected. 
- It was possible to "add" new items/things/sitemaps that already existed when they were created by other providers.
Previously a newly created item will replace the existing one accidentally when calling `NewItem.label = "label"` during the building process. `#label=` calls `provider&.update` and because provider look up is based on item's uid (item name) it found a provider, and proceeded to update/replace the existing item with the new item. This happens even though the newly created item hadn't been officially added to the provider, and in fact …
> Allow updating things/items/sitemaps by recreating them

- lib/openhab/core/things/channel.rb
- lib/openhab/core/things/thing.rb
- lib/openhab/dsl/things/builder.rb
- spec/openhab/dsl/things/builder_spec.rb
Note, some (all?) bindings provide default values for some channel attributes, e.g. `acceptedItemType`, `label`, etc. when they are not specified. This will cause thing builder to update/replace the created thing instead of leaving it unchanged. The update will cause the Thing status will change to OFFLINE, then back ONLINE.
By specifying those values during the channel creation, the Thing builder will see that the new Thing being built is exactly the same as the existing Thing, and will not update the existing thing, thereby avoiding the change in Thing status.
Demonstration:
```ruby
things.build do
thing "mqtt:topic:mything", broker: "mqtt:broker:mybroker" do
channel "signal", "number", config: { stateTopic: "xxxx" }
end
end
... 
things.build do
thing "mqtt:topic:mything", broker: …
```
> Support all attributes of channel builder

- lib/openhab/core/items/semantics.rb
- spec/openhab/core/items/semantics_spec.rb
Otherwise it gets confusing when trying to add a tag and it doesn't work as expected because a tag with the same name already exists and that tag has different attributes (parent, label, etc).
> Warn when creating a tag that already exists

- lib/openhab/core/things/item_channel_link.rb
- lib/openhab/core/things/profile_callback.rb
- spec/openhab/dsl_spec.rb
This failed because handle_command tried to call ColorItem#format_command when the channel is a String and should be able to handle any string, not related to a color
```ruby
profile("test") do |event, command:, callback:|
logger.warn "Profile called #{event} #{command}"
case event
when :command_from_item
logger.warn("command_from_item: #{command} #{command.class}")
callback.handle_command("test")
end
end
things.build do
thing "astro:moon:test"
end
items.build do
color_item "Color1" do
channel "astro:moon:test:phase#name", profile: "ruby:test"
end
end
Color1.command "0,100,100"
```
> Fix ProfileCallback#handle_command when an item is linked to a different channel type

- lib/openhab/core/items/item.rb
- lib/openhab/core/items/item_channel_links.rb
- lib/openhab/core/things/channel_uid.rb
- lib/openhab/dsl/items/builder.rb
- spec/openhab/core/items/item_spec.rb
Adding/removing links on an item would be:
```ruby
MyItem.link("mqtt:topic:foo:channel")
MyItem.link("mqtt:topic:foo:channel", profile: "transform:MAP", function: "mytransform.map")
MyItem.link things["mqtt:topic:foo"].channels["channel"]
MyItem.unlink("mqtt:topic:foo:channel")
MyItem.links.clear
```
> Add Item.link, Item.unlink, and Item.links.clear to add/remove a link to a channel

- .github/workflows/ci.yml
To address deprecation warnings:
https://github.com/openhab/openhab-jruby/actions/runs/6643125723
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> upgrade checkout action from v3 to v4

- USAGE.md
- lib/openhab/core/items.rb
- lib/openhab/core/items/dimmer_item.rb
- lib/openhab/core/items/generic_item.rb
- lib/openhab/core/items/player_item.rb
- lib/openhab/core/items/rollershutter_item.rb
- lib/openhab/core/items/semantics/enumerable.rb
- lib/openhab/core/items/switch_item.rb
- lib/openhab/dsl.rb
- lib/openhab/dsl/items/ensure.rb
- spec/openhab/dsl/items/ensure_spec.rb
Implement the idea from https://community.openhab.org/t/jruby-openhab-rules-system/110598/379
```ruby
ensure_states!
Item1.on
Item2.command(ON)
Item2.on!
```
> Add ensure_states! and bang version of command shortcuts

- lib/openhab/core/things/profile_callback.rb
- lib/openhab/dsl/things/builder.rb
- spec/openhab/dsl/things/builder_spec.rb
The accepted_item_type should be inferred from the ChannelType when not specified, so that the created channel doesn't end up with a blank accepted_item_type.
This solves the problem mentioned in #186
There "may" still be cases where it cannot be inferred(?) so I've added back the check in profile callback's handle_command.
> Infer accepted_item_type in ChannelBuilder

- lib/openhab/dsl/things/builder.rb
- spec/openhab/dsl/things/builder_spec.rb
Make it possible to configure predefined channels, e.g.:
```ruby
things.build do
thing "astro:sun:home" do
channel "rise#start", "start", config: { offset: 5 }
end
end
```
Previously this caused a "duplicate channels" error.
> Allow configuring predefined channels in Thing builder

- lib/openhab/core/events/item_state_updated_event.rb
Right now, it doesn't appear here: https://openhab.github.io/openhab-jruby/5.11/OpenHAB/Core/Events.html
> Make ItemStateUpdatedEvent appear in yard

- .github/workflows/ci.yml
bundler 3.5 was released today, which requires ruby >= 3.0 (jruby >= 9.4), which the 3.4 addon will fail trying to install. the 3.4 addon will not be receiving anymore updates, so just stop testing it
> stop testing cucumber on openHAB 3.4

- .github/workflows/ci.yml
- lib/openhab/core/sitemaps/provider.rb
- lib/openhab/dsl/sitemaps/builder.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
requires openHAB 4.1 to use AND, but fixes sitemaps to work in 4.1 at all
> Support AND'd visibility and color rules in sitemap builder

- lib/openhab/core/items.rb
- lib/openhab/core/items/dimmer_item.rb
- lib/openhab/core/items/player_item.rb
- lib/openhab/core/items/rollershutter_item.rb
- lib/openhab/core/items/switch_item.rb
- lib/openhab/dsl/items/ensure.rb
* toggle/dim/brighten just read the state; no need for them to run through ensure
* refresh never needs to be ensured
> Avoid extra ensure state check from item helper commands

- lib/openhab/core/sitemaps/provider.rb
- lib/openhab/dsl/sitemaps/builder.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
> Fix condition handling for colors and visibility in sitemap builder

- lib/openhab/osgi.rb
- lib/openhab/rspec/helpers.rb
- lib/openhab/rspec/mocks/abstract_storage_based_type_provider_wrapped_storage_service.rb
create a dummy sub-class of AbstractStorageBasedTypeProvider. we don't need any more functionality than loading of types, but we do have to create the proper ones by finding existing instances
this helps things with dynamic thing types come online
> testing: load storage based type providers

- docs/testing.md
- lib/openhab/rspec/helpers.rb
- lib/openhab/rspec/hooks.rb
- lib/openhab/rspec/mocks/thing_handler.rb
- spec/openhab/dsl/items/timed_command_spec.rb
- spec/openhab/rspec/helpers_spec.rb
this obviates the need for autoupdate_all, so deprecate that, making it a no-op, and remove associated helpers
> spec: "autoupdate" channels from mock thing handler

- lib/openhab/core/sitemaps/provider.rb
- lib/openhab/dsl/sitemaps/builder.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
Note that this is a breaking change in order to match the Sitemap xtext syntax.
Previous syntax:
```ruby
sitemaps.build do
sitemap "default", "Sitemap Label" do
...
end
end
```
New syntax:
```ruby
sitemaps.build do
sitemap "default", label: "Sitemap Label" do
...
end
end
```
> Make sitemap label a kwarg

- lib/openhab/rspec/hooks.rb
- lib/openhab/rspec/mocks/timer.rb
so that they'll hook in earlier in the process, and be mocked even between specs
this increases spec reliability by avoiding spurious "real" timers going off
> spec: change how mock timers hook in

- lib/openhab/core/items/semantics.rb
- spec/openhab/core/items/semantics_spec.rb
Make it possible to select multiple types of equipment and location, e.g.
```ruby
gLivingRoom.equipments(Semantics::Television, Semantics::Speaker, Semantics::Lightbulb)
items.locations(Semantics::Bedroom, Semantics::Bathroom)
```
> Support selecting multiple types of location and equipment

- .github/workflows/release.yml
This updates the openhab-scripting version in `Gemfile.ruby-2.6.lock`
Is this process needed, or would bundler-multilock take care of it? In any case we'll still need to check it in to git.
> Update Gemfile.ruby-2.6.lock during release process

- lib/openhab/core/entity_lookup.rb
- lib/openhab/core/items/registry.rb
No need to get all items just to check the existence of one. It got slower and slower as the number of items increase.
This change sped up the lookup considerably. I discovered this problem when trying to create 100,000 items (as a test).
In my production code, the time taken to create 100 things and 900 items went down from 16s to 6.6s
> Refactor item lookup to speed up item builder

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/yardoc.yml
Github is issuing warnings about nodejs update from v16 to v20.
https://github.com/openhab/openhab-jruby/actions/runs/7655572981
> Update github actions

- lib/openhab/core/events/item_time_series_updated_event.rb
- lib/openhab/core/items/generic_item.rb
- lib/openhab/core/profile_factory.rb
- lib/openhab/core/things/profile_callback.rb
- lib/openhab/core/types/time_series.rb
- lib/openhab/core_ext/java/instant.rb
- lib/openhab/dsl.rb
- lib/openhab/dsl/rules/builder.rb
- lib/openhab/dsl/rules/name_inference.rb
- lib/openhab/rspec/mocks/thing_handler.rb
- spec/openhab/core/types/time_series_spec.rb
- spec/openhab/dsl/rules/builder_spec.rb
- spec/openhab/dsl_spec.rb
> Add support for TimeSeries

- lib/openhab/dsl/rules/builder.rb
- lib/openhab/dsl/rules/triggers/changed.rb
- The example for using a proc for the `for` argument needs to return a Duration. Clarified this in the documentation too.
- Simplified the examples for `from/to` by removing the `for` argument
- Added a specific example of `for`
> Rearrange and fix examples for changed trigger

- lib/openhab/dsl/rules/name_inference.rb
So that if someone created a rule from a UI script, it shows the creator's uid + line number within that ui rule
> Infer id for rules created from UI

- lib/openhab/dsl/rules/triggers/watch/watch_handler.rb
Currently it looks like this:
This should be lowercased.
> Use lowercase in watch trigger label to be consistent with core

- lib/openhab/dsl/rules/name_inference.rb
- spec/openhab/log_spec.rb
Framework7 doesn't like dots in the dynamic route path.
Accessing the script using the url /settings/scripts/filename.rb:xx will result in a 404 because no route would match.
> Tweak Rule ID inference to work with F7 router

- features/logging.feature
- lib/openhab/core/items/persistence.rb
- lib/openhab/rspec/mocks/persistence_service.rb
- spec/openhab/core/items/item_spec.rb
- spec/openhab/core/items/persistence_spec.rb
Adapt to changes in Persistence actions: https://github.com/openhab/openhab-core/pull/3736
New methods were added (_until, timeseries, supports storing and retrieving future timestamps).
Core persistence methods now return a `QuantityType` for dimensioned items with a unit instead of a DecimalType. Because prior to this change in core, the jruby-library performed a conversion and returned `QuantityType` for such items, there's no impact to existing user code.
- Add `_until` methods
- Add `#persisted_state` and deprecate `#historic_state`
- Rename the `HistoricState` class to `PersistedState`, and create a deprecated alias `HistoricState` for backwards compatibility. This is because it may now hold future timestamps.
- Add `#next_state` and `#next_update`
- Deprecate `#evolution_rate`
- …
> Support changes in OH4.2 persistence

- lib/openhab/dsl/sitemaps/builder.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
https://github.com/openhab/openhab-core/pull/4183
Add `release` option in Switch mappings
```
sitemaps.build do
sitemap "default" do
switch mappings: [
{label: "On", command: ON, release: OFF, icon: "f7:power"}
]
end
end
```
> Sitemaps: support `release` option in switch mappings

- lib/openhab/core/types/date_time_type.rb
- spec/openhab/core/types/date_time_type_spec.rb
For some reason, `nil.respond_to?(:to_d)` equals true, which resulted in `DateTimeTime.new` => epoch instead of now.
> Initializing a `DateTimeType` without an argument should set it to now

- lib/openhab/core_ext/ruby/time.rb
- spec/openhab/core_ext/ruby/time_spec.rb
It seems that some APIs need an `Instant`. This allows us to use `Time.now.to_instant` as an alternative to `ZonedDateTime.now.to_instant`
> Add Time#to_instant for convenience

- lib/openhab/core/types/decimal_type.rb
- lib/openhab/core/types/quantity_type.rb
- spec/openhab/core/items/persistence_spec.rb
Currently, adding up `PersistedState`s requires adding `.state` 
```ruby
spot_prices = SpotPrice.all_states_between(start, start + 2.days)
time_series = TimeSeries.new # the default policy is replace
spot_prices.each do |spot_price|
total_price = spot_price.state +
GridTariff.persisted_state(spot_price.timestamp).state +
SystemTariff.persisted_state(spot_price.timestamp).state +
TransmissionGridTariff.persisted_state(spot_price.timestamp).state +
ElectricityTax.persisted_state(spot_price.timestamp).state
time_series.add(spot_price.timestamp, total_price)
end
```
This PR makes this possible (only the relevant part shown here):
```ruby
total_price = spot_price +
GridTariff.persisted_state(spot_price.timestamp) +
SystemTariff.persisted_state(spot_price.timestamp) + …
```
> Persistence: support direct arithmetics against PersistedState

- lib/openhab/core/actions/notification.rb
- spec/openhab/core/actions/notification_spec.rb
Notification attachment can refer to an image using the format `item:MyImageItem`
This PR accepts an Item as attachment and simply converts it to the above string
```ruby
items.build { image_item MyImageItem }
MyImageItem.update_from_file("/tmp/camera_snapshot.jpg")
Notification.send("msg", attachment: MyImageItem)
Notification.send("msg", attachment: "item:MyImageItem")
```
> Notification: support Image item as attachment

- rakelib/lint.rake
This kept tripping me up because running the local rake lint:yard didn't show the problem that the github action would otherwise catch.
> make rake lint:yard fail on warning like github action

- .rubocop.yml
- lib/openhab/dsl/sitemaps/builder.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
Buttongrid can now contain `Button` widgets which allows each button to be linked to individual item, plus each being set to different color / visibility
https://github.com/openhab/openhab-core/pull/4223
Currently, the "old" `button` option for buttongrid is still supported too, so it's backwards compatible with oh4.1
Adding buttons to a buttongrid with positional arguments
```ruby
sitemaps.build do
sitemap "remote" do
buttongrid item: RCButton do
button 1, 1, "BACK", "Back", "f7:return"
button 1, 2, "HOME", "Menu", "material:apps"
button 1, 3, "YELLOW", "Search", "f7:search"
button 2, 2, "UP", "Up", "f7:arrowtriangle_up"
button 4, 2, "DOWN", "Down", "f7:arrowtriangle_down"
button 3, 1, "LEFT", "Left", "f7:arrowtriangle_left"
button 3, 3, "RIGHT", "Right", "f7:arrowtriangle_right"
button …
```
> Sitemaps: support Button widgets inside buttongrids

- lib/openhab/core.rb
- lib/openhab/core/events/item_event.rb
- lib/openhab/dsl.rb
#133 implemented context access for when UI rules/scripts are manually run/triggered. We didn't encounter any issues for that particular method of execution, because there is no trigger module ID involved.
In UI based rules, $ctx keys are prepended with the module id of the trigger that triggered the rule execution (e.g. item state change), so currently the library won't find a match for, e.g. `event` because it's stored as `$ctx["<moduleid>.event"]` 
It appears that nobody is using this library for UI based rules, otherwise we would've received bug reports/complaints.
> Fix access to context variables in UI rules

- lib/openhab/log.rb
- spec/openhab/log_module.rb
- spec/openhab/log_spec.rb
Resolve #310
This PR sets the logging prefix as follows:
| Location                          | Prefix                                                                                                                                          |
| --------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- |
| Inside a rule with inferred id    | Before:<br>`org.openhab.automation.jrubyscripting.rule.line:NN` <br><br>After:<br>`org.openhab.automation.jrubyscripting.filename.rule.line:NN` |
| Inside a rule with an explicit ID | Before:<br>`org.openhab.automation.jrubyscripting.rule.ruleid`  <br><br>After:<br>`org.openhab.automation.jrubyscripting.filename.rule.ruleid`  |
The …
> Prepend script name to logger calls within rules, scripts, and profiles

- lib/openhab/core/rules/rule.rb
- lib/openhab/dsl/rules/builder.rb
- spec/openhab/dsl/rules/builder_spec.rb
Create the rule in a disabled state instead of not creating it at all, so it can be enabled in the future.
> Support creating a rule in an initially disabled state

- lib/openhab/core/types/date_time_type.rb
https://github.com/openhab/openhab-core/pull/4364 broke `spec/openhab/core/types/date_time_type_spec.rb:32`
> DateTimeType implements Java's Comparable in openHAB 4.3

- lib/openhab/core/sitemaps/provider.rb
- spec/openhab/core/sitemaps/provider_spec.rb
See: https://github.com/openhab/openhab-core/blob/8d54ccefef1ec06b16542bf28af5452742cfaba7/bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java#L340
Without this fix, you'd have to refresh the ui (e.g. BasicUI) to "see" the change in the given example below. With the fix, BasicUI will automatically refresh.
```ruby
sitemaps.build do
sitemap "test" do
text label: "Old1"
text label: "Old2"
end
end
items.build { switch_item TestSwitch1 }
received_command(TestSwitch1) do
sitemaps.build do
sitemap "test" do
text label: "New"
end
end
end
```
Steps:
- Load the above script, but don't send a command to TestSwitch1 yet.
- Load the sitemap in BasicUI / browser. It should show two text widgets Old1, Old2
- Now send a command to …
> Sitemap updates not propagated to listeners

- lib/openhab/core/items/date_time_item.rb
- lib/openhab/dsl.rb
- spec/openhab/core/items/date_time_item_spec.rb
Support `DateTimeType.new("2020-01-01 12:30")` as well as `DateTimeItem1.update("2020-01-01 12:30")` for all versions of openHAB.
See: https://github.com/openhab/openhab-core/pull/4370 and DateTimeType also supports parsing a string containing epoch, so let it try parsing the string too.
> Support space separator between date and time

- lib/openhab/core/entity_lookup.rb
- lib/openhab/dsl.rb
- spec/openhab/dsl/sitemaps/builder_spec.rb
Anyplace you want to be able to directly reference entities, you should be able to use their collections as well to dynamically find them.
> Move #items and #things to EntityLookup

- lib/openhab/core/events/timer_event.rb
Depends on https://github.com/openhab/openhab-core/pull/4378
> Add `#time_only?` and `#offset` to TimerEvent

- lib/openhab/dsl/items/timed_command.rb
- spec/openhab/dsl/items/timed_command_spec.rb
Regression from #312
There were two problems
- When timed command expired, the cancel rule got called because it wasn't disabled
- In the timed command block, it was possible to call resume when the timed command had expired, resulting in an expired timed command that isn't cleaned up / removed.
> Fix timed command expire

- spec/openhab/core/types/date_time_type_spec.rb
The case of `DateTimeType.parse("00:00+1000")` is parsed by Time.parse in DSL.try_parse_time_like, which takes into account the current time and the system time zone in interpreting the given "time+timezone" string.
This is why it has been intermittent in the past: depending on the time the spec was running, and the system time zone of the machine running the spec, the resulting _date_ could be either today or yesterday whereas the previous spec was pinning the date to today's date.
Here's a demonstration, notice the date in the last example:
```
irb(main):047> Time.now
=> 2024-09-17 10:16:27.302101 +1000
irb(main):048> Time.now.utc
=> 2024-09-17 00:16:33.278331 UTC
irb(main):049> Time.parse("0:00+00:00")
=> 2024-09-17 00:00:00 +0000
irb(main):050> Time.parse("0:00-00:18")
=> 2024-09-16 …
```
> DateTimeType spec fix

- lib/openhab/core/actions/notification.rb
> update notification doc links to point to current openHAB

- rakelib/docs.rake
- spec/openhab/core/things/thing_spec.rb
- spec/openhab/dsl/things/builder_spec.rb
instead of MQTT, which recently got a new dependency that's not installing for some reason
> use dscalarm binding for tests

- lib/openhab/dsl/items/builder.rb
- spec/openhab/dsl/items/builder_spec.rb
mired is 1/Temperature, but the rest of openHAB treats it as Temperature, so special case it
> special case mired unit dimension inference in items builder

- lib/openhab/core/items/number_item.rb
- spec/openhab/core/items/number_item_spec.rb
Returns a Range from a state description, and applies units if possible
> Add NumberItem#range

- lib/openhab/core/types/hsb_type.rb
The change was introduced in 
https://github.com/openhab/openhab-core/pull/4433
> Use Units::MIRED instead of "mired" in HSBType

- lib/openhab/dsl/items/builder.rb
the unit symbol for it changed, and aliases were added, so we need to make sure to parse it first, and then compare against the actual constant for it
> fix mired detection in OH 4.3

- lib/openhab/core/items/proxy.rb
- spec/openhab/core/items/proxy_spec.rb
Enumerable and predicate methods will now behave better when they refer to stale proxies - filtering methods will just remove them. I run into this occasionally when I have multiple rules firing, and some of them are adding or removing items - and calling items.locations would raise a NoMethodError for #location? due to a race condition. This should no longer happen - it will just ignore the now-stale items.
> fix race condition when using semantic methods

- lib/openhab/dsl/items/builder.rb
- spec/openhab/dsl/items/builder_spec.rb
Also add fluent aliases for adding multiple channels, groups and tags, and clarify documentation.
Also fixes calling `channel` on a `GroupItemBuilder`, because it was being shadowed by `Terse#channel`, because `DSL` was getting included unecessarily (we only need `EntityLookup`, which is already explicitly included).
Fixes #374
> Allow passing an array of channels to item builder

- lib/openhab/core_ext/java/local_date.rb
- lib/openhab/core_ext/java/local_time.rb
- spec/openhab/core_ext/java/local_date_spec.rb
- spec/openhab/core_ext/java/local_time_spec.rb
This will fix the following problem:
```ruby
items.build { date_time_item DT1 }
DT1.update "7:30"
```
Previously, DT1 will interpret that as 7:30Z instead of 7:30 local time.
> Use system timezone when converting from LocalDate/LocalTime to instant

- lib/openhab/core/emulate_hash.rb
- lib/openhab/core/things/proxy.rb
- lib/openhab/core/things/thing.rb
- spec/openhab/core/things/thing_spec.rb
Sometimes, we'd have to set a Thing's property because that's where the representationProperty resides, and it needs to be set when creating a Thing in order to avoid it being duplicated in the inbox.
The current method is to call `thing.set_property(key, value)`. This PR enables the syntax `thing.properties[key] = value`.
> Support setting Thing property using hash-like syntax `[]=`

- lib/openhab/core/items/semantics/semantic_tag.rb
Change from 
```
#<OpenHAB::Core::Items::Semantics::Thermometer(Equipment_Sensor) label="" description="" synonyms=[""]>
```
to:
```
#<OpenHAB::Core::Items::Semantics::Thermometer (Equipment_Sensor) label="" description="" synonyms=[""]>
```
> Add a space between semantic name and its parent in #inspect

- lib/openhab/core/types/quantity_type.rb
- spec/openhab/core/types/quantity_type_spec.rb
- spec/openhab/dsl_spec.rb
There was a bug in our spec which core was happily allowing:
`(1 | "1/W").compare_to(1 | "W")` used to return `0`.
openHAB 5.0 now throws an exception when comparing invertible unit. 
Relevant [PR](https://github.com/openhab/openhab-core/pull/4571)
> Fix QuantityType#eql? raising exception on incompatible QuantityType unit

- lib/openhab/core/registry.rb
- lib/openhab/dsl/items/builder.rb
- lib/openhab/rspec/mocks/persistence_service.rb
- spec/openhab/core/items/registry_spec.rb
- spec/openhab/dsl/items/builder_spec.rb
ManagedProvider's Item.provider returned nil
This stopped us from notifying the ManagedProvider of any changes.
Using object (reference) comparison doesn't work for AbstractManagedProvider (JSON db stuff) nor for GenericItemProvider because they don't keep a reference to the objects. They would recreate them on the fly every time we call `get`, so the object returned cannot be compared by reference.
The original reason for comparing by reference was to check whether an item was updated or remained the same, especially within the spec.
This PR changed the verification approach by checking to see if provider.update was ever called. This achieved the same goal of ensuring that unchanged items during build do not trigger unnecessary update notifications to listeners.
> Fix problem in getting the provider for entities of ManagedProvider

- USAGE.md
- lib/openhab/core/types/quantity_type.rb
- lib/openhab/core_ext/java/duration.rb
- lib/openhab/core_ext/java/local_date.rb
- lib/openhab/core_ext/java/local_time.rb
- lib/openhab/core_ext/java/period.rb
- lib/openhab/core_ext/java/temporal_amount.rb
- lib/openhab/core_ext/java/zoned_date_time.rb
- lib/openhab/core_ext/ruby/date.rb
- lib/openhab/core_ext/ruby/date_time.rb
- lib/openhab/core_ext/ruby/time.rb
- spec/openhab/core_ext/java/duration_spec.rb
- spec/openhab/core_ext/java/local_date_spec.rb
- spec/openhab/core_ext/java/local_time_spec.rb
- spec/openhab/core_ext/java/zoned_date_time_spec.rb
- spec/openhab/core_ext/ruby/date_spec.rb
- spec/openhab/core_ext/ruby/time_spec.rb
Aiming to support including Time `QuantityType` in arithmetic operations (+/-, comparisons) against Duration and Date/Time. 
Some example usage:
```ruby
NumberTimeItem.state > 1.hour
ZonedDateTime.now + NumberTimeItem.state
```
`Period` isn't specifically treated as thoroughly in this PR, since I'm not sure it's used all that often.
> Support Date/Time operations against Time QuantityType

- Gemfile.lock
- lib/openhab/core/entity_lookup.rb
- lib/openhab/core/items.rb
- lib/openhab/dsl.rb
- openhab-scripting.gemspec
no longer necessary with Ruby 3.1 minimum version
> remove ruby2_keywords

- lib/openhab/core/items/image_item.rb
- lib/openhab/core/types/raw_type.rb
- spec/openhab/core/items/image_item_spec.rb
to satisfy the Rubocop Performance/StringBytesize cop
also avoid an extraneous Base64 encode for an image, when we can directly create the RawType
> Add RawType#bytesize

- CHANGELOG.md
- lib/openhab/core/entity_lookup.rb
- lib/openhab/core/items/generic_item.rb
- lib/openhab/core/items/item.rb
- lib/openhab/core/items/persistence.rb
- lib/openhab/core/items/proxy.rb
- lib/openhab/core/items/semantics.rb
- lib/openhab/core/proxy.rb
- lib/openhab/core/things/proxy.rb
- lib/openhab/dsl/items/ensure.rb
- lib/openhab/dsl/items/timed_command.rb
- spec/openhab/core/items/proxy_spec.rb
If a user keeps a ref to an item, and that item disappears, calling a method on that item will now raise a helpful StaleProxyError, instead of a NoMethodError on nil
The proxy code was significantly refactored, and Thing will also inherit the same stale proxy  I also removed the $things registry lookup on every access of a thing, using the same event subscriber mechanism as Item.
I also moved several methods from GenericItem to Item, so that Proxy can detect that those methods should exist even for dummy/stale items.
>  Improve errors when an item no longer exists

- lib/openhab/core/proxy.rb
- spec/openhab/core/items/proxy_spec.rb
> Fix issue with kwargs methods being treated as ruby2_keywords sometimes

- lib/openhab/yard/markdown_helper.rb
such as {RUBY_ENGINE_VERSION} etc. in the docs.
> don't strip unknown links to preserve path replacements

- lib/openhab/core/items/persistence.rb
- spec/openhab/core/items/persistence_spec.rb
https://github.com/openhab/openhab-core/pull/4461
- Add `riemann_type` kwarg to `average`, `deviation`, and `variance` persistence methods
- Add `riemann_sum_xxx` persistence methods
> Persistence: support riemann_sum methods

- lib/openhab/core.rb
- lib/openhab/core/events/item_state_changed_event.rb
- lib/openhab/core/events/item_state_updated_event.rb
- spec/openhab/core/events/item_state_changed_event_spec.rb
- spec/openhab/core/events/item_state_updated_event_spec.rb
See https://github.com/openhab/openhab-core/pull/4606
This affects the event's #inspect method, so marking this as ehancement, not just documentation changes
> Support `ItemStateUpdatedEvent#last_state_update` and `ItemStateChangedEvent#last_state_change`

- lib/openhab/core.rb
- lib/openhab/core/items.rb
- lib/openhab/core/items/call_item.rb
- lib/openhab/core/items/color_item.rb
- lib/openhab/core/items/contact_item.rb
- lib/openhab/core/items/date_time_item.rb
- lib/openhab/core/items/dimmer_item.rb
- lib/openhab/core/items/generic_item.rb
- lib/openhab/core/items/image_item.rb
- lib/openhab/core/items/item.rb
- lib/openhab/core/items/location_item.rb
- lib/openhab/core/items/number_item.rb
- lib/openhab/core/items/persistence.rb
- lib/openhab/core/items/player_item.rb
- lib/openhab/core/items/rollershutter_item.rb
- lib/openhab/core/items/string_item.rb
- lib/openhab/core/items/switch_item.rb
- spec/openhab/core/items/item_spec.rb
https://github.com/openhab/openhab-core/pull/4351
YARD doesn't seem to pick up # @!method xxx inside an empty class.
```ruby
class PlayerItem < GenericItem
end
```
`#play` won't be picked up.
see it here (it's not there): 
https://openhab.github.io/openhab-jruby/5.37/OpenHAB/Core/Items/PlayerItem.html (missing `play?`, `play`, etc)
https://openhab.github.io/openhab-jruby/5.37/OpenHAB/Core/Items/ContactItem.html (missing `open?`, `closed?`)
If I added one dummy method even with `@!visibility private`, yard would then pick it up.
Moving them up into the class preamble is the solution for now for empty classes unless YARD fixed this.
This affects `PlayerItem`, `ContactItem`
Reported: https://github.com/lsegal/yard/issues/1613
> Add `GenericItem#was`, `#was?`, `#was_xxx?` predicates, document `Item#last_state`, `#last_state_change`, and `#last_state_update` methods

- lib/openhab/core/timer.rb
- lib/openhab/core/value_cache.rb
- lib/openhab/dsl.rb
- spec/openhab/core/value_cache_spec.rb
```ruby
timer = after(1.hour) { logger.info "Timer from Ruby" }
shared_cache[:mytimer] = timer
```
```ruby
shared_cache[:mytimer]&.reschedule(10.seconds.from_now)
```
> Support passing timer objects to other scripts via shared_cache

- lib/openhab/core/items/semantics.rb
- spec/openhab/core/items/semantics_spec.rb
Resolve #432
By default, semantic methods `#points`, `#locations`, and `#equipments` will match subclasses of the given tags, e.g. `items.locations(Semantics::Room)` will return all semantic locations Room and all its subclasses (LivingRoom, Bedroom, Kitchen, etc).
This PR adds a `subclass:` parameter so that `items.locations(Semantics::Room, subclass: false)` will return only those with the actual `Room` tag and not any of the subtags of `Room`.
This is useful for example to differentiate between `OccupancySensor` vs `MotionSensor` (which is a subclass of `OccupancySensor`)
> Semantic Tags: add `subclasses:` parameter to allow exact match and exclude all subclasses of the given tags

- lib/openhab/core/value_cache.rb
This avoids the warning
```
/openhab/conf/automation/ruby/.gem/9.4.12.0/gems/openhab-scripting-5.37.0/lib/openhab/core/value_cache.rb:224: warning: singleton on non-persistent Java type Java::OrgOpenhabCoreAutomationModuleScriptRulesupportInternal::CacheScriptExtension::TrackingValueCacheImpl (https://github.com/jruby/jruby/wiki/Persistence)
```
> shared_cache: prepend on the $sharedCache class, not its singleton class

- lib/openhab/core/items.rb
last_state can be nil when the item was just created and has no previous state
> handle nil last_state for was_xx? predicate

- lib/openhab/console/irb.rb
As #438 still proved to be difficult, this tackles it a different way.
JRuby 10 was just released, and with it, comes irb 1.14.3, which our curent irb code is happy with. Since the console is only available in openHAB 5, we could just reduce this version requirement to match JRuby10, and ship OH5 with JRuby10. That would also solve the irb issue.
> Require irb ~> 1.14 to allow the version shipped with JRuby 10

- USAGE.md
Standardize tables with no spaces around `|`
> minor grammatical errors in console gem command

- rakelib/test.rake
We only need the cucumber rake tasks, not all of cucumber, unless we're actually running that task
> Don't require cucumber from rake task

- spec/openhab/core/items/persistence_spec.rb
Symbol#to_s will be frozen in Ruby 3.5
> make sure string is non-frozen before mutating it

- lib/openhab/core/events/abstract_event.rb
- lib/openhab/core/items/item.rb
- lib/openhab/core/things/profile_callback.rb
- lib/openhab/core/value_cache.rb
* just ignore them on events (we're not going to receive the object from java multiple times anyway)
* cache the object externally for ProfileCallback
* don't memoize ValueCache#to_proc
> fix various "instance vars on non-persistent Java type" warnings

- lib/openhab/core.rb
- lib/openhab/core/items/generic_item.rb
- lib/openhab/core/items/metadata.rb
- lib/openhab/core/items/metadata/namespace_hash.rb
- lib/openhab/core/items/registry.rb
- lib/openhab/dsl.rb
- lib/openhab/dsl/items/builder.rb
- lib/openhab/dsl/items/tags.rb
- lib/openhab/dsl/rules/builder.rb
- lib/openhab/dsl/rules/triggers.rb
- lib/openhab/dsl/things/builder.rb
To speed up the library's loading time, make some parts autoloaded (only loaded when needed)
- UI rules won't need to load the whole file-based `rule` creation support
- Most scripts don't need to load the items/things/sitemap builder
- item metadata handling
Resolve #418 
```
$ find lib -name 'builder.rb' -exec ls -lh {} \; | sort -h
-rw-rw-r-- 1 openhab openhab 17K Mar 25 01:00 lib/openhab/dsl/things/builder.rb
-rw-rw-r-- 1 openhab openhab 33K Apr  3 17:10 lib/openhab/dsl/items/builder.rb
-rw-rw-r-- 1 openhab openhab 59K Apr  3 16:26 lib/openhab/dsl/sitemaps/builder.rb
$ find lib -name 'builder.rb' -exec wc -l {} \; | sort -h
407 lib/openhab/dsl/things/builder.rb
864 lib/openhab/dsl/items/builder.rb
1488 lib/openhab/dsl/sitemaps/builder.rb
```
dsl/rules are only needed by file-based, so …
> Autoload builders (items, things, sitemaps, rules) and item metadata

- .github/workflows/release.yml
- Rakefile
- docs/js/versions.js
- templates/default/layout/html/layout.erb
- Put versions.js in docs/js/versions.js - yard doesn't include this in its output
- at the end of github yard workflow, put this file into gh-pages branch, in /js/versions.js
- Refer to this script in our pages with full url `https://openhab.github.io/openhab-jruby/js/versions.js`. By using this absolute url, local yard server will also pick it up (once it has been committed there)
This makes versions.js not be a part of each version's subdirectory in gh-pages. Instead we only have one global copy that's kept updated.
> check versions.js into gh-pages /js directory

- docs/js/versions.js
- lib/openhab/rspec/karaf.rb
- templates/default/layout/html/versions.erb
Also includes a bug fix s/openhab-scripting/openhab-jruby/
Note, I had to move `require_relative "mocks/synchronous_executor"` to the top of the file due to the errors in https://github.com/openhab/openhab-jruby/actions/runs/14594673803/job/40939084574
> Apply goto-page onto the main version-switcher buttons

- lib/openhab/core.rb
should we call this `user_data_folder` matching the one in core?
> Add `OpenHAB::Core.user_data_folder`

- lib/openhab/core/items/semantics.rb
The additions in the core semantic tags had some duplicates and inconsistencies in synonyms, as a result lookups resulted in wrong tags being found because we searched in synonyms and labels first.
One example is the tag `App`. The Tag `Application` (which is not the same as `App`) had `App` in its synonyms, causing `Semantics::App` to point to `Application` instead.
This PR makes sure we look up by ID first.
The conflicting synonyms need to be fixed in core too: https://github.com/openhab/openhab-core/pull/4885
> Semantics tag lookup: prioritize ID over label or synonym

- lib/openhab/core/events/abstract_event.rb
Payloads are not guaranteed to be JSON, so if they aren't just return it directly.
> Fix AbstractEvent#payload for non-JSON payloads
